"""extend risk findings with structured assessment fields

Revision ID: 09e8cd42ed01
Revises: 95a9867c5b92
Create Date: 2026-08-10 00:50:33.534526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09e8cd42ed01'
down_revision: Union[str, Sequence[str], None] = '95a9867c5b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand (not part of the model) so this is safe to
    # run against a table that already has rows — the ORM-level Python
    # defaults in models.py cover new inserts; these only backfill existing
    # ones during the migration itself.
    op.add_column('risk_findings', sa.Column('categories', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('risk_findings', sa.Column('evidence', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('risk_findings', sa.Column('confidence_score', sa.Float(), nullable=False, server_default='0.5'))
    op.add_column('risk_findings', sa.Column('affected_components', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('risk_findings', sa.Column('recommended_regression_scope', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('risk_findings', sa.Column('release_recommendation', sa.String(), nullable=False, server_default='proceed'))
    op.add_column('risk_findings', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_findings', 'created_at')
    op.drop_column('risk_findings', 'release_recommendation')
    op.drop_column('risk_findings', 'recommended_regression_scope')
    op.drop_column('risk_findings', 'affected_components')
    op.drop_column('risk_findings', 'confidence_score')
    op.drop_column('risk_findings', 'evidence')
    op.drop_column('risk_findings', 'categories')
    # ### end Alembic commands ###
