"""initial schema

Revision ID: 7accf472f013
Revises: 
Create Date: 2026-08-08 03:06:37.936690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7accf472f013'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_provider_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repositories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repo_id', sa.Uuid(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider_config_id', sa.Uuid(), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_config_id'], ['llm_provider_configs.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_provider_config_id'), 'analysis_runs', ['provider_config_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_repo_id'), 'analysis_runs', ['repo_id'], unique=False)
    op.create_table('commits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repo_id', sa.Uuid(), nullable=False),
    sa.Column('sha', sa.String(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('diff_stats', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commits_repo_id'), 'commits', ['repo_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repo_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_repo_id'), 'test_cases', ['repo_id'], unique=False)
    op.create_table('flaky_test_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_case_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('pattern_summary', sa.Text(), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flaky_test_findings_analysis_run_id'), 'flaky_test_findings', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_flaky_test_findings_test_case_id'), 'flaky_test_findings', ['test_case_id'], unique=False)
    op.create_table('risk_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('repo_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_findings_analysis_run_id'), 'risk_findings', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_risk_findings_repo_id'), 'risk_findings', ['repo_id'], unique=False)
    op.create_table('test_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('commit_id', sa.Uuid(), nullable=False),
    sa.Column('ci_provider', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('raw_log_ref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_runs_commit_id'), 'test_runs', ['commit_id'], unique=False)
    op.create_table('test_suggestions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('repo_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('target_function', sa.String(), nullable=True),
    sa.Column('suggested_test_code', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_suggestions_analysis_run_id'), 'test_suggestions', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_test_suggestions_repo_id'), 'test_suggestions', ['repo_id'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_run_id', sa.Uuid(), nullable=False),
    sa.Column('test_case_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_test_case_id'), 'test_results', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_test_results_test_run_id'), 'test_results', ['test_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_results_test_run_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_test_case_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_test_suggestions_repo_id'), table_name='test_suggestions')
    op.drop_index(op.f('ix_test_suggestions_analysis_run_id'), table_name='test_suggestions')
    op.drop_table('test_suggestions')
    op.drop_index(op.f('ix_test_runs_commit_id'), table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_index(op.f('ix_risk_findings_repo_id'), table_name='risk_findings')
    op.drop_index(op.f('ix_risk_findings_analysis_run_id'), table_name='risk_findings')
    op.drop_table('risk_findings')
    op.drop_index(op.f('ix_flaky_test_findings_test_case_id'), table_name='flaky_test_findings')
    op.drop_index(op.f('ix_flaky_test_findings_analysis_run_id'), table_name='flaky_test_findings')
    op.drop_table('flaky_test_findings')
    op.drop_index(op.f('ix_test_cases_repo_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_commits_repo_id'), table_name='commits')
    op.drop_table('commits')
    op.drop_index(op.f('ix_analysis_runs_repo_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_provider_config_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_table('repositories')
    op.drop_table('llm_provider_configs')
    # ### end Alembic commands ###
