"""add failure findings and llm invocations

Revision ID: 95a9867c5b92
Revises: 7accf472f013
Create Date: 2026-08-08 03:19:37.017843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a9867c5b92'
down_revision: Union[str, Sequence[str], None] = '7accf472f013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_invocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_invocations_analysis_run_id'), 'llm_invocations', ['analysis_run_id'], unique=False)
    op.create_table('failure_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_result_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failure_findings_analysis_run_id'), 'failure_findings', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_failure_findings_test_result_id'), 'failure_findings', ['test_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_failure_findings_test_result_id'), table_name='failure_findings')
    op.drop_index(op.f('ix_failure_findings_analysis_run_id'), table_name='failure_findings')
    op.drop_table('failure_findings')
    op.drop_index(op.f('ix_llm_invocations_analysis_run_id'), table_name='llm_invocations')
    op.drop_table('llm_invocations')
    # ### end Alembic commands ###
