"""extend test suggestions with structured assessment fields

Revision ID: fc97630b89c5
Revises: 09e8cd42ed01
Create Date: 2026-08-10 01:41:42.852571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc97630b89c5'
down_revision: Union[str, Sequence[str], None] = '09e8cd42ed01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand (not part of the model), same rationale as
    # the risk_findings migration: safe to run against a table with existing
    # rows. ORM-level Python defaults in models.py cover new inserts.
    op.add_column('test_suggestions', sa.Column('test_type', sa.String(), nullable=False, server_default='unit'))
    op.add_column('test_suggestions', sa.Column('evidence', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('test_suggestions', sa.Column('assumptions', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('test_suggestions', sa.Column('confidence', sa.Float(), nullable=False, server_default='0.5'))
    op.add_column('test_suggestions', sa.Column('uncovered_risks', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('test_suggestions', sa.Column('recommended_follow_up_validation', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_suggestions', 'recommended_follow_up_validation')
    op.drop_column('test_suggestions', 'uncovered_risks')
    op.drop_column('test_suggestions', 'confidence')
    op.drop_column('test_suggestions', 'assumptions')
    op.drop_column('test_suggestions', 'evidence')
    op.drop_column('test_suggestions', 'test_type')
    # ### end Alembic commands ###
